### ISSUE TITLE
terminal doesn't work at all..

### ISSUE THREAD

**Issue by Nuc1eoN** [hawaii-desktop/hawaii-terminal#12]
I get the error:
````
"Qt Warning - invalid keysym: dead_actute" 
````
A black window opens, only with a cursor in the middle.

Using ArchLinux and the package from AUR. I'm *not* using the git versions of Qt5.

EDIT:
Hm strange I get the exact same error message when using communi https://aur.archlinux.org/packages/communi-desktop/ ... it seems to work though.

**Comment by plfiorini** [comment]
Should be fixed now
