### ISSUE TITLE
[!] Fail to start after installation! Please have a look!

### ISSUE THREAD

**Issue by MuSamDu** [hawaii-desktop/hawaii-terminal#16]
First of all, I "git cloned" your codes, then i compiled and installed the terminal, following your instructions written in readme, but i changed the target directory into "/usr". After all when i'm trying to run the command "hawaii-terminal" in both "Konsole" and "Terminator", i got these and nothing happened after this:

>QQmlApplicationEngine failed to load component
>qrc:/qml/main.qml:42 Type TerminalComponent unavailable
>qrc:/qml/TerminalComponent.qml:28 module "Hawaii.Terminal.QMLTermWidget" is not installed
>
>kf5.kiconthemes: "Theme tree: (Breeze)"

Please make a try to tell me what the hell, thanks a lot!

**Comment by plfiorini** [comment]
Projects using extra-cmake-modules such as this one need an additional argument when installing on /usr:

```sh
cmake -DCMAKE_INSTALL_PREFIX=/usr -DKDE_INSTALL_USE_QT_SYS_PATHS=ON ..
```

Added to README.md just now
