### ISSUE TITLE
Is this featuring Hula Dancing?

### ISSUE THREAD

**Issue by livibetter** [hawaii-desktop/hawaii-terminal#20]
I don't have Qt 5.5 and the ECM, so I didn't install to check out myself. Although, I also didn't seen any possible resource files for that, there might still be a chance, therefore I must open an issue to ask.

If Hawaii Terminal does have Hula Dancing, then I am willing to install those dependencies, though I am not sure if Qt 5.5 would compile on my old laptop, if its scale is like Qt4, it'd be fine. Or would they dance in slow-mo.

**Comment by plfiorini** [comment]
It doesn't do the Hula Dance but it can do the split (terminal view) like Jean-Claude Van Damme. :)

Qt 5 is split in more modules but you don't need all of them. It's available in most, if not all, distros by now.

**Comment by livibetter** [comment]
Oh, why did you have to mention that, now I remember seeing him splitting once on a talk show.

I use Gentoo (we do have Qt 5.5.1 available), so for most packages, we have to compile, not like I have issues with that, just some packages are incredibly fat and greedy in resources during the building stage, and slow in compilation *<sub>(whispering c~plus~plus~)<sub>*.

Anyway, thanks for answering my question.
